model:
  channel_last: true
  scale_shift_norm: true
  num_attention_heads: 4
  attention_resolutions:
  - 8
  - 16
  - 32
  resblock_resample: true
  num_attention_head_channels: 64
  base_channels: 256
  channel_mult:
  - 1
  - 1
  - 2
  - 2
  - 4
  - 4
  num_res_blocks: 2
  dropout: 0.1
  model_var_type: learned_range
  image_shape:
  - 256
  - 256
  - 3
  
diffusion:
  beta_strategy: linear
  max_timesteps: 1000
  model_var_type: learned_range
  respacing_step: 1