defaults:
  - /proto_configs/train@_here_
  - _self_


## batch size
# Assumes 8 GPU. 
# According to the paper, total batch size should be 2048.
batch_size: 8
accum: 4
n_iters: 2500000

## dump
# progress: False
output_dir: ./logdir/imagenet_64to256_efficient_unet
# save_interval: 10000
# show_interval: 10
# gen_interval: 20000
# dump_grad_norm: True

## checkpointing
# resume: False

## loss
lr: 1e-4
# loss_scaling: 1.0
# clip_grad: 1.0
lr_scheduler: cosine

